"""Create place table

Revision ID: 416d9a263573
Revises: 
Create Date: 2021-12-10 15:14:56.674001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '416d9a263573'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('imagen', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licores_id'), 'licores', ['id'], unique=False)
    op.create_index(op.f('ix_licores_nombre'), 'licores', ['nombre'], unique=False)
    op.create_index(op.f('ix_licores_precio'), 'licores', ['precio'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_licores_precio'), table_name='licores')
    op.drop_index(op.f('ix_licores_nombre'), table_name='licores')
    op.drop_index(op.f('ix_licores_id'), table_name='licores')
    op.drop_table('licores')
    # ### end Alembic commands ###
